services:
  aws-deepracer:
    build:
      context: .
      dockerfile: Dockerfile.deepracer
    container_name: ros2_container_aws
    tty: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority