FROM osrf/ros:jazzy-desktop-full

SHELL ["/bin/bash", "-c"]

WORKDIR /app

#COPY ros2_ws /app/ros2_ws
COPY ros_entrypoint.sh /ros_entrypoint.sh

# Build iniziale del workspace
RUN source /opt/ros/jazzy/setup.bash && \
    #cd /app/ros2_ws && \
    colcon build

# Entrypoint e comando
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash", "-c", "ros2 launch bringup_pkg all_nodes.launch.py"]