services:
  ros2_system: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_container
    tty: true
    environment:
      - DISPLAY
    volumes:
      - ./ros2_ws:/app/ros2_ws       
      - /tmp/.X11-unix:/tmp/.X11-unix
