FROM osrf/ros:foxy-desktop

SHELL ["/bin/bash", "-c"]

WORKDIR /app

# Copia solo il workspace
COPY ros2_ws /app/ros2_ws
COPY ros_entrypoint.sh /ros_entrypoint.sh

# Build iniziale del workspace
RUN source /opt/ros/foxy/setup.bash && \
    cd /app/ros2_ws && \
    colcon build

# Entrypoint e comando
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash", "-c", "ros2 launch bringup_pkg all_nodes.launch.py"]