services:
  ros2_system-jazzy:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ros2_container
    tty: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros2_ws:/app/ros2_ws

  aws-deepracer:
    build:
      context: .
      dockerfile: Dockerfile.foxy
    container_name: ros2_container_aws
    tty: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
